;factorial code

.MODEL SMALL
.STACK 100H
.DATA

 MSG1 DB 'ENTER A NUMBER: $'
 MSG2 DB 0DH,0AH,'FACTORIAL RESULT= $'
 
.CODE
  MAIN PROC
   MOV AX,@DATA
   MOV DS,AX
   
   MOV AH,9         ;DISPLAY MSG2
   LEA DX,MSG1
   INT 21H
   
   CALL INDEC       ; CALL INDEC PROCEDURE
   PUSH AX          ;STORE RESULT IN STACK
   
    MOV AH,9        ;DIPLAY MSG2
    LEA DX,MSG2
    INT 21H 
   
    
   POP AX            ; POP FROM STACK FOR FACTORIA
   MOV BX,AX
   SUB BX,1
  
   CALL FACTORIAL     ; CALL FACTORIAL PROCEDURE
    
  
    ;POP AX
    CALL OUTDEC       ;RESULT STORE IN AX AND CALL OUTDEC
  
  
   
   PUSH AX  
   CALL PRINT_NEW_LINE  ;PRINT NEW LINE
   
   
   MOV AH,4CH          ;EXIT CODE
   INT 21H
 
 
 MAIN  ENDP  
  
  
 FACTORIAL PROC
;TAKE INPUT AX
;INPUT BX
;STORE RESULT IN AX 

  FACT_LOOP:
   MUL BX
   DEC BX
   CMP BX,1
   JNLE FACT_LOOP
  
  RET
 FACTORIAL ENDP
  
 
  
  INCLUDE INDEC.ASM
  INCLUDE OUTDEC.ASM  
  INCLUDE PRINT_NEW_LINE.ASM 
  ;INCLUDE FACTORIAL_PRO.ASM

  
  ENDP MAIN